mydata<-matrix(c(0,-1,3,-1,0,1,3,-1,1,-1,-2,-1,1,-2,2,1,-1,0),nrow=6,ncol=3,byrow=FALSE)
df=as.data.frame(mydata, empirical=TRUE)
colnames(df)<-c("y","x1","x2")
df
sapply(df,mean)
sapply(df,sd)
covm<-cov(df)
covm
corm<-cor(df)
corminstall.packages("QuantPsyc")
library("QuantPsyc")
install.packages("boot")
install.packages("MASS")
library("QuantPsyc")
mod1<-lm(y~x1, data=df)
lm.beta(mod1)
mod1z<-lm(scale(df$y)~scale(df$x1))
mod2<-lm(y~x2,data=df)
lm.beta(mod2)
mod2z<-lm(scale(df$y)~scale(df$x2))
multiple1<-lm(y~x1+x2,data=df)
multiple1z<-lm(scale(df$y)~scale(df$x1)+scale(df$x2))

setwd("~/Desktop/204B")
getwd()
mydata<-read.csv("Tworek&Cimpian.csv")
head(mydata)
mod1<-lm(Should_Score~Belief_in_Just_World, data=mydata)
summary(mod1)
mod2<-lm(Should_Score~Belief_in_Just_World+Good_Score+excluded, data=mydata)
summary(mod2)
AIC(mod1)
AIC(mod2)
anova(mod1,mod2)
mod3<-lm(Should_Score~Belief_in_Just_World*Good_Score+Belief_in_Just_World*excluded+Good_Score*excluded, data=mydata)
summary(mod3)
AIC(mod3)
AIC(mod2)
anova(mod2,mod3)
full.model=lm(Should_Score~excluded+RavensProgressiveMatrix_sum+Inherence_Bias+Good_Score+Ought_Score+Belief_in_Just_World, data=mydata)
backwards.model=step(full.model,direction=c("backward"))
intercept.model=lm(Should_Score~1, data=mydata)
forwards.model=step(intercept.model,direction=c("forward"),scope=~excluded+RavensProgressiveMatrix_sum+Inherence_Bias+Good_Score+Ought_Score+Belief_in_Just_World, data=mydata)
