#3(a)
pdata<-read.csv("pigeon.csv")
head(pdata)
plot(pdata$trial, pdata$pecks, xlab="Trial", ylab="Number of Pecks", main="Pigeon Pecking Patterns Over a Series of Trials")
#3(b)&(d)
mod1=lm(pdata$pecks~pdata$trial)
summary(mod1)
plot(pdata$trial, pdata$pecks, xlab="Trial", ylab="Number of Pecks", main="Linear Model for Pigeon Pecking Patterns Over a Series of Trials")
abline(lm(formula=pdata$trial~pdata$pecks), col="blue")
mod2=nls(pecks~a+(b*trial+sin(((2*pi)/5)*trial)),start=list(a=0,b=5),data=pdata)
summary(mod2)
c=coef(mod2)
plot(pdata$trial, pdata$pecks, xlab="Trial", ylab="Number of Pecks", main="Two Slope Sine Curve Model")
curve(c[1]+(c[2]*x+sin(x)), add=TRUE, lty=1, col="red")
mod3=nls(pecks~a+(b*trial+c*sin(trial)),start=list(a=0, b=1.5, c=1.5), data=pdata)
summary(mod3)
plot(pdata$trial, pdata$pecks, xlab="Trial", ylab="Number of Pecks", main="Three Slope Sine Curve Model")
d=coef(mod3)
curve(d[1]+(d[2]*x+d[3]*sin(x)), add=TRUE, lty=1, col="green")
#3(c)
AIC(mod1);AIC(mod2);AIC(mod3)
BIC(mod1);BIC(mod2);BIC(mod3)
anova(mod2,mod3)
#4(a)
setwd("/Users/madelinecraft/Desktop")
mdata<-read.csv("moderationFinalExam.csv")
m1<-lm(y~x1+x2+x1*x2, data=mdata)
summary(m1)
#4(b)
lowtime=-1*sd(mdata$x2)+mean(mdata$x2)
meantime=mean(mdata$x2)
hightime=sd(mdata$x2)+mean(mdata$x2)
coef(m1)
exp_low<-coef(m1)[1]+coef(m1)[2]*lowtime+coef(m1)[3]*mdata$x1+coef(m1)[4]*lowtime*mdata$x1
exp_mean<- coef(m1)[1]+coef(m1)[2]*meantime+coef(m1)[3]*mdata$x1+coef(m1)[4]*meantime*mdata$x1
exp_high<- coef(m1)[1]+coef(m1)[2]*hightime+coef(m1)[3]*mdata$x1+coef(m1)[4]*hightime*mdata$x1
mdata<-mdata[order(mdata$x1),]
head(mdata)
plot(mdata$x1, mdata$y, type="n", main="Moderated Associations of x1 and y", ylab="Association of x1 and y", xlab="x1")
lines(mdata$x1, exp_low, lwd=3, col="blue")
lines(mdata$x1, exp_mean, lwd=3, col="red")
lines(mdata$x1, exp_high, lwd=3, col="green")
legend(-.15, 3.5, lty=c(1,1,1), col=c("blue","red","green"),legend=c("-1SD", "0SD", "1SD"))
#4(c)
m1<-lm(y~x1+x2+x1*x2, data=mdata)
summary(m1)
cx1<-mdata$x1-mean(mdata$x1)
cx2<-mdata$x2-mean(mdata$x2)
m2<-lm(y~cx1+cx2+cx1*cx2, data=mdata)
summary(m2)
#5(a)
gdata<-read.table("Menarche.txt")
names(gdata)=c("ID","Age","Period","Time","Fat")
set.seed(100)
theseIDs<-sample(unique(gdata$ID),50)
subdata<-gdata[gdata$ID %in% theseIDs,]
subdata
p <- ggplot(data = subdata, aes(x = Age, y = Fat, group = ID))+ xlab("Current Age")+ylab("% Body Fat")+ggtitle("Relationship Between Female Age and Percet Body Fat")
p+geom_line()
#5(b)
library(nlme)
mod1=lme(Fat~Age+Period, random=~1|ID, method="REML", data=gdata)
summary(mod1)
6.0496^2
3.8862^2
36.5977/(36.5977+15.1026)
#5(c)
mod2=lme(Fat~Age+Period, random=~1+Age|ID, method="REML", data=gdata)
summary(mod2)
#5(d)
AIC(mod1);AIC(mod2)
BIC(mod1);BIC(mod2)
anova(mod1, mod2)
#6(a)
tdata<-read.csv("terrormanagement.csv")
summary(tdata)
dim(tdata)
table(tdata$religfam)
table(tdata$thinkd)
table(tdata$religious)
class(tdata$religious)
class(tdata$thinkd)
class(tdata$religfam)
median(tdata$thinkd)
tdata$religfam=as.factor(tdata$religfam)
tdata$religious=as.factor(tdata$religious)
tdata$thinkd=as.factor(tdata$thinkd)
ftable(tdata$thinkd, tdata$religfam)
#6(b)
mod1=glm(tdata$religious~tdata$thinkd, family="binomial")
summary(mod1)
mod2=glm(tdata$religious~tdata$thinkd+tdata$religfam, family="binomial")
summary(mod2)
mod3=glm(tdata$religious~tdata$thinkd+tdata$religfam+tdata$thinkd*tdata$religfam, family="binomial")
summary(mod3)
#6(c)
AIC(mod1);AIC(mod2)
BIC(mod1);BIC(mod2)
anova(mod1, mod2)
pchisq(119.95, 1, lower.tail=FALSE)
AIC(mod2);AIC(mod3)
BIC(mod2);BIC(mod3)
anova(mod2, mod3)
pchisq(16.337, 4, lower.tail=FALSE)
#6(d)
tdata$religious=as.integer(tdata$religious)
tdata$thinkd=as.integer(tdata$thinkd)
tdata$religious=tdata$religious-1
plot(religious~thinkd, xlab="Degree to which an Individual Thinks about Mortality", ylab="Probability of Identifying as Religious", main="Identifying as Religious as a Funtion of Thinking about Mortality", data=tdata)
points(religious[religfam=="1"]~thinkd[religfam=="1"], pch=16, col="green", data=tdata)
points(religious[religfam=="0"]~thinkd[religfam=="0"],pch=1, col="purple", data=tdata)
c=coef(mod3)
coef(mod3)
curve(exp(c[1]+c[2]*x)/(1+exp(c[1]+c[2]*x)), add=TRUE, lty=1, col="purple")
curve(exp(c[1]+c[2]*x+c[3]+c[4]*x)/(1+exp(c[1]+c[2]*x+c[3]+c[4]*x)), add=TRUE, lty=2, col="green")
legend(3.3,.4, c("Non-Religious Family", "Religious Family"), col=c("purple", "green"), lty=c(1,2))

#6(e)
#log(p/(1-p))= -0.25 -0.02*thinkd2 -0.03*thinkd3 +1.02*thinkd4 +0.47*thinkd5 +0.76*religfam +0.46*thinkd2*religfam +1.03*thinkd3*religfam +0.50*thinkd4*religfam +1.88*thinkd5*religfam
exp(-0.25)/(1+exp(-0.25))
exp(-0.25-0.02)/(1+exp(-0.25-0.02))
exp(-0.25-0.03)/(1+exp(-0.25-0.03))
exp(-0.25+1.02)/(1+exp(-0.25+1.02))
exp(-0.25+0.47)/(1+exp(-0.25+0.47))
exp(-0.25+0.76)/(1+exp(-0.25+0.76))
exp(-0.25-0.02+0.76+0.46)/(1+exp(-0.25-0.02+0.76+0.46))
exp(-0.25-0.03+0.76+1.03)/(1+exp(-0.25-0.03+0.76+1.03))
exp(-0.25+1.02+0.76+0.50)/(1+exp(-0.25+1.02+0.76+0.50))
exp(-0.25+0.47+0.76+1.88)/(1+exp(-0.25+0.47+0.76+1.88))




